services:
  - type: web
    name: my-express-server
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

staticSites:
  - name: my-react-client
    buildCommand: npm install && npm run build
    publishDir: build
